using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using widlife_server.Internal;
using widlife_server.Services;
using wildlife_server.Data;
using wildlife_server.Models;

namespace wildlife_server.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    // http://localhost:5000/api/fish
    public class FishController : ControllerBase
    {
        private readonly IFishService FishService;

        public FishController(IFishService fishService, DataContext context)
        {
            FishService = fishService;
        }
        
        // POST: api/fish
        // autogenerated
        [HttpPost]
        public async Task<ActionResult<ResponseWrapper<Fish>>> CreateFish(Fish fish)
        {
            var response = await FishService.CreateFish(fish);
            return Ok(response);
        }

        // GET: api/fish
        // returns all fish
        [HttpGet]
        public async Task<ActionResult<ResponseWrapper<ICollection<Fish>>>> GetAllFish()
        {
            var response = await FishService.GetAllFish();
            return Ok(response);
        }
        
        // GET: api/fish/:id
        // returns specific fish based on id
        [HttpGet("{id}")]
        public async Task<ActionResult<ResponseWrapper<Fish>>> GetFishById(int id)
        {
            var response = await FishService.GetFishById(id);
            return Ok(response);
        }
    }
}
